<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2018 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xff="http://www.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altova-xfi altovaext array clitype fn iso4217 ix java link map math sps xbrldi xbrli xff xfi xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML1" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2018 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=5"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.6in; margin-right:0.6in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } div.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<xsl:for-each select="$XML1">
					<xsl:for-each select="MICEX_DOC">
						<div>
							<span style="font-family:Arial; font-size:10; font-style:italic; ">
								<xsl:text>Исх. №: </xsl:text>
							</span>
							<xsl:for-each select="DOC_REQUISITES">
								<xsl:for-each select="@DOC_NO">
									<span style="font-family:Arial; font-size:10; font-style:italic; font-weight:bold; ">
										<xsl:value-of select="string(.)"/>
									</span>
								</xsl:for-each>
								<span style="font-family:Arial; font-size:10; font-style:italic; ">
									<xsl:text> от </xsl:text>
								</span>
								<xsl:for-each select="@DOC_DATE">
									<span style="font-family:Arial; font-size:10; font-style:italic; font-weight:bold; ">
										<xsl:variable name="altova:seqContentStrings_0">
											<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
											<xsl:text>. </xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
											<xsl:text>. </xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
										</xsl:variable>
										<xsl:variable name="altova:sContent_0" select="string($altova:seqContentStrings_0)"/>
										<xsl:value-of select="$altova:sContent_0"/>
									</span>
								</xsl:for-each>
							</xsl:for-each>
						</div>
						<div style="font-family:Arial; font-size:11; font-weight:bold; text-align:right; ">
							<span>
								<xsl:text>EQM20</xsl:text>
							</span>
						</div>
						<div style="font-family:Arial; font-size:11; font-weight:bold; ">
							<span>
								<xsl:text>Небанковская кредитная организация-центральный контрагент</xsl:text>
							</span>
						</div>
						<div style="font-family:Arial; font-size:11; font-weight:bold; ">
							<span>
								<xsl:text>«Национальный Клиринговый Центр» (Акционерное общество)</xsl:text>
							</span>
						</div>
						<br/>
						<xsl:for-each select="EQM20">
							<div style="font-family:Arial; font-size:14; font-weight:bold; text-align:center; ">
								<span style="text-align:center; ">
									<xsl:text>Отчет о торгово-клиринговых счетах</xsl:text>
								</span>
							</div>
							<div style="font-family:Arial; font-size:14; font-weight:bold; text-align:center; ">
								<xsl:for-each select="@Weekday">
									<span>
										<xsl:value-of select="string(.)"/>
									</span>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="@ReportDate">
									<span>
										<xsl:variable name="altova:seqContentStrings_1">
											<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
											<xsl:text>.</xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
											<xsl:text>.</xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
										</xsl:variable>
										<xsl:variable name="altova:sContent_1" select="string($altova:seqContentStrings_1)"/>
										<xsl:value-of select="$altova:sContent_1"/>
									</span>
								</xsl:for-each>
							</div>
							<br/>
							<span style="font-family:Arial; font-size:12; ">
								<xsl:text>Наименование участника клиринга:</xsl:text>
							</span>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<xsl:for-each select="@FirmName">
								<span style="font-family:Arial; font-size:12; font-weight:bold; ">
									<xsl:value-of select="string(.)"/>
								</span>
							</xsl:for-each>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<span style="font-family:Arial; font-size:12; ">
								<xsl:text>(</xsl:text>
							</span>
							<xsl:for-each select="@MainFirmId">
								<span style="font-family:Arial; font-size:12; font-weight:bold; ">
									<xsl:value-of select="string(.)"/>
								</span>
							</xsl:for-each>
							<span style="font-family:Arial; font-size:12; font-weight:normal; ">
								<xsl:text>)</xsl:text>
							</span>
							<xsl:for-each select="FIRM">
								<br/>
								<span style="font-family:Arial; font-size:12; ">
									<xsl:text>Идентификатор участника клиринга: </xsl:text>
								</span>
								<xsl:for-each select="@FirmID">
									<span style="font-family:Arial; font-size:12; font-weight:bold; ">
										<xsl:value-of select="string(.)"/>
									</span>
								</xsl:for-each>
								<br/>
								<br/>
								<xsl:for-each select="INFO">
									<xsl:choose>
										<xsl:when test="@InfoType = &apos;B&apos;">
											<span style="font-family:Arial; font-size:12; font-weight:bold; text-decoration:underline; ">
												<xsl:text>Информация о денежных позициях</xsl:text>
											</span>
										</xsl:when>
										<xsl:when test="@InfoType = &apos;T&apos;">
											<span style="font-family:Arial; font-size:12; font-weight:bold; text-decoration:underline; ">
												<xsl:text>Информация о торгово-клиринговых счетах</xsl:text>
											</span>
										</xsl:when>
									</xsl:choose>
									<br/>
									<br/>
									<xsl:for-each select="BANKACC">
										<span style="font-family:Arial; font-size:12; font-style:italic; font-weight:normal; ">
											<xsl:text>Код денежной позиции:</xsl:text>
										</span>
										<span>
											<xsl:text>&#160; </xsl:text>
										</span>
										<xsl:for-each select="@BankAccId">
											<span style="font-family:Arial; font-size:12; font-weight:bold; ">
												<xsl:value-of select="string(.)"/>
											</span>
										</xsl:for-each>
										<br/>
										<br/>
										<xsl:for-each select="TRDACC">
											<xsl:choose>
												<xsl:when test="../@BankAccPoolType = &apos;Y&apos;">
													<xsl:choose>
														<xsl:when test="../../@InfoType = &apos;B&apos;">
															<table style="border-collapse:collapse; font-family:Arial; font-size:10; font-weight:normal; " border="1">
																<xsl:variable name="altova:CurrContextGrid_2" select="."/>
																<tbody>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Тип денежной позиции</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@BankAccType">
																					<xsl:choose>
																						<xsl:when test=". = &quot;S&quot;">
																							<span>
																								<xsl:text>для учета собственных средств</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test=". = &apos;L&apos;">
																							<span>
																								<xsl:text>для учета средств клиентов</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test=". = &apos;D&apos;">
																							<span>
																								<xsl:text>для учета средств, переданных в доверительное управление</xsl:text>
																							</span>
																						</xsl:when>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Соответствие Расчетному коду имущественного пула</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@BankAccPoolType">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																</tbody>
															</table>
															<br/>
															<table style="border:0; border-collapse:collapse; border-left:0; border-right:0; font-family:Arial; font-size:10; font-weight:normal; text-align:inherit; word-wrap:break-word; " border="1" height="1">
																<xsl:variable name="altova:CurrContextGrid_3" select="."/>
																<thead style="border:0; border-top:0; text-align:inherit; ">
																	<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Код</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>валюты</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Код</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>организации</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Наименование</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>организации</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Расчетный код</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Номер счета</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>обеспечения</xsl:text>
																			</span>
																		</th>
																	</tr>
																</thead>
																<tbody>
																	<xsl:for-each select="RECORDS">
																		<tr style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:center; vertical-align:top; ">
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:for-each select="@CurrencyId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; ">
																				<xsl:for-each select="@ClearingCenterId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<xsl:for-each select="@ClearingCenterName">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@RealAccount">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@NccRealAccount">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</tr>
																	</xsl:for-each>
																	<tr style="border-left:0; border-right:0; height:1px; text-align:center; vertical-align:top; ">
																		<td colspan="5" style="border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set"/>
																	</tr>
																</tbody>
															</table>
															<br/>
														</xsl:when>
														<xsl:when test="../../@InfoType = &quot;T&quot;">
															<span style="font-family:Arial; font-size:12; font-style:italic; ">
																<xsl:text>Торгово-клиринговые счета: </xsl:text>
															</span>
															<table style="border:0; border-collapse:collapse; border-left:0; border-right:0; font-family:Arial; font-size:10; font-weight:normal; text-align:inherit; word-wrap:break-word; " border="1" height="1">
																<xsl:variable name="altova:CurrContextGrid_4" select="."/>
																<thead style="border:0; border-top:0; text-align:inherit; ">
																	<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Код Торгово-</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>клирингового</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>счета</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Наименование</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>Торгово-клирингового</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>счета</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Состояние</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>Торгово-</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>клирингового </xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>счета</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Субсчет</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>депо</xsl:text>
																			</span>
																			<br/>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Соответствие</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>ТКС Т+</xsl:text>
																			</span>
																			<br/>
																		</th>
																	</tr>
																</thead>
																<tbody>
																	<xsl:for-each select="RECORDS">
																		<tr style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:center; vertical-align:top; ">
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@TrdAccId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; ">
																				<xsl:for-each select="@TrdAccName">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:for-each select="@TrdAccStatus">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@DepUnitId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@TrdAccPoolMatch">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</tr>
																	</xsl:for-each>
																	<tr style="border-left:0; border-right:0; height:1px; text-align:center; vertical-align:top; ">
																		<td colspan="5" style="border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set"/>
																	</tr>
																</tbody>
															</table>
															<br/>
														</xsl:when>
													</xsl:choose>
												</xsl:when>
												<xsl:otherwise>
													<xsl:choose>
														<xsl:when test="../../@InfoType = &apos;B&apos;">
															<table style="border-collapse:collapse; font-family:Arial; font-size:10; font-weight:normal; " border="1">
																<xsl:variable name="altova:CurrContextGrid_5" select="."/>
																<tbody>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Тип денежной позиции</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@BankAccType">
																					<xsl:choose>
																						<xsl:when test=". = &quot;S&quot;">
																							<span>
																								<xsl:text>для учета собственных средств</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test=". = &apos;L&apos;">
																							<span>
																								<xsl:text>для учета средств клиентов</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:when test=". = &apos;D&apos;">
																							<span>
																								<xsl:text>для учета средств, переданных в доверительное управление</xsl:text>
																							</span>
																						</xsl:when>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Без допуска к клирингу с частичным обеспечением по денежным средствам</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@FullCoveredBuy">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Соответствие Расчетному коду имущественного пула</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@BankAccPoolType">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																	<tr>
																		<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																			<span>
																				<xsl:text>Соответствие Расчетному коду Единого пула</xsl:text>
																			</span>
																		</td>
																		<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																			<xsl:for-each select="..">
																				<xsl:for-each select="@BankAccUnifiedPool">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</xsl:for-each>
																		</td>
																	</tr>
																</tbody>
															</table>
															<br/>
															<table style="border:0; border-collapse:collapse; border-left:0; border-right:0; font-family:Arial; font-size:10; font-weight:normal; text-align:inherit; word-wrap:break-word; " border="1" height="1">
																<xsl:variable name="altova:CurrContextGrid_6" select="."/>
																<thead style="border:0; border-top:0; text-align:inherit; ">
																	<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Код</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>валюты</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Код</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>организации</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Наименование</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>организации</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Номер счета /</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>Расчетный код</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Номер счета</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>обеспечения</xsl:text>
																			</span>
																		</th>
																		<th colspan="3" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Признаки переводов денежных средств</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Счет для </xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>уплаты </xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>возмещения </xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>и комиссии</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Взимается</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>оборотная</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>часть</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>комиссионного</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>вознаграждения</xsl:text>
																			</span>
																		</th>
																		<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>Изменения</xsl:text>
																			</span>
																		</th>
																	</tr>
																	<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>с Т0 на Т+</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>при исполнении</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>с Т0 на Т+</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>в размере</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>нетто-обязательства</xsl:text>
																			</span>
																		</th>
																		<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																			<span>
																				<xsl:text>с Т+ на Т0</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>в размере</xsl:text>
																			</span>
																			<br/>
																			<span>
																				<xsl:text>нетто-требования</xsl:text>
																			</span>
																		</th>
																	</tr>
																</thead>
																<tbody>
																	<xsl:for-each select="RECORDS">
																		<tr style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:center; vertical-align:top; ">
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:for-each select="@CurrencyId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; ">
																				<xsl:for-each select="@ClearingCenterId">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<xsl:for-each select="@ClearingCenterName">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@RealAccount">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@NccRealAccount">
																					<span>
																						<xsl:value-of select="string(.)"/>
																					</span>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@TransferSettleRUR">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<xsl:for-each select="@TransferNettoRUR">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; " nowrap="set">
																				<xsl:for-each select="@ReturnSettleRUR">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:for-each select="@CommPaymentAcc">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:for-each select="@TaxPaymentAcc">
																					<xsl:choose>
																						<xsl:when test=". = &quot;Y&quot;">
																							<span>
																								<xsl:text>Да</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>Нет</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</xsl:for-each>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																				<xsl:choose>
																					<xsl:when test="@DataChanged = &quot;Y&quot;">
																						<span>
																							<xsl:text>*</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:otherwise/>
																				</xsl:choose>
																			</td>
																		</tr>
																	</xsl:for-each>
																	<tr style="border-left:0; border-right:0; height:1px; text-align:center; vertical-align:top; ">
																		<td colspan="11" style="border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set"/>
																	</tr>
																</tbody>
															</table>
															<span style="font-family:Arial; font-size:10; ">
																<xsl:text>* Признак проведения изменений</xsl:text>
															</span>
															<br/>
															<br/>
														</xsl:when>
														<xsl:when test="../../@InfoType = &quot;T&quot;">
															<span style="font-family:Arial; font-size:12; font-style:italic; ">
																<xsl:text>Торгово-клиринговые счета: </xsl:text>
															</span>
															<xsl:choose>
																<xsl:when test="@TrdAccDeposit = &apos;N&apos;">
																	<table style="border:0; border-collapse:collapse; border-left:0; border-right:0; font-family:Arial; font-size:10; font-weight:normal; text-align:inherit; word-wrap:break-word; " border="1" height="1">
																		<xsl:variable name="altova:CurrContextGrid_7" select="."/>
																		<thead style="border:0; border-top:0; text-align:inherit; ">
																			<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Код Торгово-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клирингового</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Наименование</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>Торгово-клирингового</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Состояние</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>Торгово-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клирингового </xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Счет депо</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Раздел</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета депо</xsl:text>
																					</span>
																					<br/>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Соответствие</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>раздела</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счету</xsl:text>
																					</span>
																					<br/>
																				</th>
																				<th colspan="3" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Признаки переводов ценных бумаг </xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Без допуска к</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клирингу с</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>частичным </xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>обеспечением</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>по ценным бумагам</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Заключение</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>сделок купли-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>продажи в случае</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>неисполнения</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>обязательств по</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>Сделкам Т+</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Торгово-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клиринговый</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счет Единого</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>пула</xsl:text>
																					</span>
																				</th>
																				<th rowspan="2" style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Изменения</xsl:text>
																					</span>
																				</th>
																			</tr>
																			<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>с Т0 на Т+</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>при исполнении</xsl:text>
																					</span>
																				</th>
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>с Т0 на Т+</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>в размере</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>нетто-обязательства</xsl:text>
																					</span>
																				</th>
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>с Т+ на Т0</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>в размере</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>нетто-требования</xsl:text>
																					</span>
																				</th>
																			</tr>
																		</thead>
																		<tbody>
																			<xsl:for-each select="RECORDS">
																				<tr style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:center; vertical-align:top; ">
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@TrdAccId">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; ">
																						<xsl:for-each select="@TrdAccName">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@TrdAccStatus">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@DepAccId">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@DepUnitId">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@P_Type">
																							<xsl:choose>
																								<xsl:when test=". = &quot;1&quot;">
																									<span>
																										<xsl:text>Счет в НРД</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=".= &quot;2&quot;">
																									<span>
																										<xsl:text>Расчетный код</xsl:text>
																									</span>
																								</xsl:when>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@TransferSettleSecurity">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@TransferNettoSecurity">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@ReturnSettleSecurity">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@FullCoveredSell">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@DisableREPO">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@UnifiedPoolTrdAcc">
																							<xsl:choose>
																								<xsl:when test=". = &quot;Y&quot;">
																									<span>
																										<xsl:text>Да</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:otherwise>
																									<span>
																										<xsl:text>Нет</xsl:text>
																									</span>
																								</xsl:otherwise>
																							</xsl:choose>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:choose>
																							<xsl:when test="@DataChanged = &quot;Y&quot;">
																								<span>
																									<xsl:text>*</xsl:text>
																								</span>
																							</xsl:when>
																							<xsl:otherwise/>
																						</xsl:choose>
																					</td>
																				</tr>
																			</xsl:for-each>
																			<tr style="border-left:0; border-right:0; height:1px; text-align:center; vertical-align:top; ">
																				<td colspan="13" style="border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set"/>
																			</tr>
																		</tbody>
																	</table>
																</xsl:when>
																<xsl:when test="@TrdAccDeposit = &apos;Y&apos;">
																	<table style="border-collapse:collapse; font-family:Arial; font-size:10; font-weight:normal; " border="1">
																		<xsl:variable name="altova:CurrContextGrid_8" select="."/>
																		<tbody>
																			<tr>
																				<td style="font-weight:bold; padding-left:5pt; padding-right:5pt; width:4.17in; ">
																					<span>
																						<xsl:text>Торгово-клиринговый счет для заключения депозитных договоров</xsl:text>
																					</span>
																				</td>
																				<td style="padding-left:5pt; padding-right:5pt; text-align:center; width:1in; ">
																					<span>
																						<xsl:text>Да</xsl:text>
																					</span>
																				</td>
																			</tr>
																		</tbody>
																	</table>
																	<br/>
																	<table style="border:0; border-collapse:collapse; border-left:0; border-right:0; font-family:Arial; font-size:10; font-weight:normal; text-align:inherit; word-wrap:break-word; " border="1" height="1">
																		<xsl:variable name="altova:CurrContextGrid_9" select="."/>
																		<thead style="border:0; border-top:0; text-align:inherit; ">
																			<tr style="border-top:0; font-family:Arial; font-size:10; font-weight:bold; text-align:inherit; vertical-align:top; ">
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Код Торгово-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клирингового</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Наименование</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>Торгово-клирингового</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Состояние</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>Торгово-</xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>клирингового </xsl:text>
																					</span>
																					<br/>
																					<span>
																						<xsl:text>счета</xsl:text>
																					</span>
																				</th>
																				<th style="border-left:0; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set" valign="middle">
																					<span>
																						<xsl:text>Изменения</xsl:text>
																					</span>
																				</th>
																			</tr>
																		</thead>
																		<tbody>
																			<xsl:for-each select="RECORDS">
																				<tr style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:center; vertical-align:top; ">
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="@TrdAccId">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:left; ">
																						<xsl:for-each select="@TrdAccName">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:for-each select="@TrdAccStatus">
																							<span>
																								<xsl:value-of select="string(.)"/>
																							</span>
																						</xsl:for-each>
																					</td>
																					<td style="border-bottom:0; border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set">
																						<xsl:choose>
																							<xsl:when test="@DataChanged = &quot;Y&quot;">
																								<span>
																									<xsl:text>*</xsl:text>
																								</span>
																							</xsl:when>
																							<xsl:otherwise/>
																						</xsl:choose>
																					</td>
																				</tr>
																			</xsl:for-each>
																			<tr style="border-left:0; border-right:0; height:1px; text-align:center; vertical-align:top; ">
																				<td colspan="4" style="border-left:0; border-top:0; font-family:Arial; font-size:10; font-weight:normal; padding-left:5pt; padding-right:5pt; text-align:center; " nowrap="set"/>
																			</tr>
																		</tbody>
																	</table>
																</xsl:when>
															</xsl:choose>
															<span style="font-family:Arial; font-size:10; ">
																<xsl:text>* Признак проведения изменений</xsl:text>
															</span>
															<br/>
															<br/>
														</xsl:when>
													</xsl:choose>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:for-each>
										<br/>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
